-- Snowflake environment bootstrap for AI Data Engineering workloads

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS AI_DATA_ENG;
CREATE SCHEMA IF NOT EXISTS AI_DATA_ENG.DOC_PROCESSING;
CREATE SCHEMA IF NOT EXISTS AI_DATA_ENG.RAG_PIPELINE;

CREATE WAREHOUSE IF NOT EXISTS AI_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS AI_ENGINEER_ROLE;

GRANT USAGE ON DATABASE AI_DATA_ENG TO ROLE AI_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA AI_DATA_ENG.DOC_PROCESSING TO ROLE AI_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA AI_DATA_ENG.RAG_PIPELINE TO ROLE AI_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AI_DATA_ENG.DOC_PROCESSING TO ROLE AI_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AI_DATA_ENG.RAG_PIPELINE TO ROLE AI_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE AI_WH TO ROLE AI_ENGINEER_ROLE;
